import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const errors = [];
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text().slice(0, 200)); });
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message.slice(0, 200)));
await page.goto('http://localhost:3000/', { waitUntil: 'networkidle', timeout: 60000 }).catch(() => page.goto('http://localhost:3000/', { waitUntil: 'domcontentloaded' }));
await page.waitForTimeout(2500);
if (errors.length) errors.forEach((e) => console.log('ERR:', e));
else console.log('no console errors');
await browser.close();
